obj-$(CONFIG_OPPO_COMMON_SOFT)  +=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)  +=  oppo_devinfo/
obj-$(CONFIG_OPPO_CUSTOM)  += oppo_custom/
obj-$(CONFIG_OPPO_CRITICALLOG)  +=  oppo_criticallog/
obj-$(CONFIG_OPPO_HYPNUS)     +=  oppo_hypnus/
obj-$(CONFIG_OPPO_ALS_CALI)   +=  oppo_als_cali_value/

#ifdef VENDOR_EDIT
#//Kun.Hu@PSW.TECH 2018/11/15, Add phoenix base
obj-y     +=  oppo_phoenix/
#endif /* VENDOR_EDIT */