#ifdef VENDOR_EDIT
#HANG_OPPO_ALL
#//Kun.Hu@PSW.TECH 2018/11/15, Add phoenix base
obj-y += phoenix_base.o
obj-y += phoenix_dump.o
#//Bright.Zhang@PSW.TECH 2018/12/24, Add phenix base
obj-y += monitor_bootup.o
#endif /* VENDOR_EDIT */


